export const customShaftsData = [
  {
    id: 1,
    name: 'Modell Torino',
    no: '10390',
    category: 'sandalen',
    type: 'herren',
    price: 10999,
    image: '/images/customShoes/1.png',
    description: 'This is a custom shaft',
  },
  {
    id: 2,
    name: 'Modell Torino',
    no: '10391',
    type: 'herren',
    category: 'halbschuhe',
    price: 1099,
    image: '/images/customShoes/2.png',
    description: 'This is a custom shaft',
  },
  {
    id: 3,
    name: 'Modell Berlin',
    no: '10400',
    type: 'herren',
    category: 'sportschuhe',
    price: 12999,
    image: '/images/customShoes/3.png',
    description: 'Herren Sportschuhe',
  },
  {
    id: 4,
    name: 'Modell Hamburg',
    no: '10401',
    type: 'herren',
    category: 'knochelhoheschuhe',
    price: 13999,
    image: '/images/customShoes/4.png',
    description: 'Herren Knochelhoheschuhe',
  },
  {
    id: 3,
    name: 'Modell Berlin',
    no: '10400',
    type: 'damen',
    category: 'sportschuhe',
    price: 12999,
    image: '/images/customShoes/3.png',
    description: 'Herren Sportschuhe',
  },
  {
    id: 4,
    name: 'Modell Hamburg',
    no: '10401',
    type: 'damen',
    category: 'knochelhoheschuhe',
    price: 13999,
    image: '/images/customShoes/4.png',
    description: 'Herren Knochelhoheschuhe',
  }
]; 